package com.wellplayed.gaming.store;

import com.wellplayed.gaming.store.models.*;
import com.wellplayed.gaming.store.repositories.BuyRepository;
import com.wellplayed.gaming.store.repositories.ClientRepository;
import com.wellplayed.gaming.store.repositories.ComponentRepository;
import com.wellplayed.gaming.store.repositories.TicketRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.time.LocalDateTime;
import java.util.Arrays;

@SpringBootApplication
public class WellPlayedApplication {

    private LocalDateTime localDateTime = LocalDateTime.now();

    public static void main(String[] args) {
        SpringApplication.run(WellPlayedApplication.class , args);
    }

    @Bean
    public CommandLineRunner initData(ClientRepository clientRepository, ComponentRepository componentRepository, BuyRepository buyRepository, TicketRepository ticketRepository) {
        return args -> {
            Client julianBrunelli = new Client("JulianBrunelli@outlook.com", "1234", 43317950, 1925, "36 e/ 123 y 124", "2216178731");
            clientRepository.save(julianBrunelli);

            Component mouseHyperX1 = new Component("Mouse", "HyperX", "Pulsefire Core - RGB Gaming Mouse", "The HyperX Pulsefire Core delivers the essentials for gamers looking for a solid, comfortable, wired RGB gaming mouse. The Pixart 3327 optical sensor gives players precise, smooth tracking with no hardware acceleration, and has native DPI settings up to 6200 DPI. The ergonomically-designed Pulsefire Core has textured side grips for a comfortable, no-slip grip, and its symmetrical shape is suitable for both palm and claw grip. It features high-quality switches with crisp tactile feedback rated for up to 20 million clicks. Customize lighting, DPI settings, and macros for 7 programmable buttons with HyperX NGENUITY software and set your mouse up just the way you want it. The large skates on Pulsefire Core help deliver accurate aiming by giving you a smooth, controlled glide as you move the mouse.", Arrays.asList("Pixart 3327 optical sensor","6200 DPI / 220 IPS / 30G", "Customizable with HyperX NGENUITY software", "Weight: 87g"), Arrays.asList("Pink"), Arrays.asList("https://hyperx.com/cdn/shop/files/hyperx_pulsefire_core_white_pink_0_main_1080x.jpg?v=1695137191", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_core_white_pink_3_front_angled_1080x.jpg?v=1695137191", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_core_white_pink_7_rgb_1080x.jpg?v=1695137221", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_core_white_pink_6_bottom_1080x.jpg?v=1695137221", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_core_white_pink_5_front_back_1080x.jpg?v=1695137191"), 29.99, 5);

            Component mouseHyperX2 = new Component("Mouse", "HyperX", "Pulsefire Haste - Itachi Edition - Gaming Mouse", "The HyperX Pulsefire Haste is built for elite gamers looking to gain every fraction of a second possible in their quest to be the best. Weighing in at 59 grams, this full-featured, responsive honeycomb shell mouse has everything you need, just without the extra weight. Blaze your own trail with this limited-edition design inspired by Itachi’s time with the Akatsuki. TTC Golden micro switches provide satisfying, reliable clicks and are rated for 60 million clicks, so you will not have to worry about missing inputs. The flexible HyperFlex USB cable and the virgin-grade PTFE skates work together to give you a smooth, easy glide to make dominating the game simple.", Arrays.asList("Limited Itachi Edition", "Ultra-light and built for speed", "Customizable with HyperX NGENUITY Software", "Grip Tape Included"), Arrays.asList("Black-Red"), Arrays.asList("https://hyperx.com/cdn/shop/files/hyperx_pulsefire_haste_itachi_red_0_main_1080x.jpg?v=1695249485", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_haste_itachi_red_2_back_angled_1080x.jpg?v=1695249485", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_haste_itachi_red_4_side_1080x.jpg?v=1695249485", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_haste_itachi_red_5_front_back_1080x.jpg?v=1695249485", "https://hyperx.com/cdn/shop/files/hyperx_pulsefire_haste_itachi_red_7_rgb_1080x.jpg?v=1695249485"), 59.99, 100);


            Component keyboardHyperX1 = new Component("Keyboard", "HyperX", "Alloy Elite 2 - Mechanical Gaming Keyboard", "For gamers, streamers, and multi-taskers who need to have more control at their fingertips, the HyperX Alloy Elite 2 is the keyboard for you. With dedicated media keys and a large volume wheel, this fully-featured gaming keyboard’s ready for everything from video editing to watching movies. It’s built with ultra-reliable HyperX mechanical switches balanced for speed and responsiveness, so you can trust your key inputs. The switches’ exposed LEDs pair with the translucent HyperX Pudding Keycaps to give your RGB lighting extra brightness compared to solid-color keycaps. Customize the signature light bar and create lighting profiles with intuitive HyperX NGENUITY software for a brilliant display of colors. Use the software to personalize your setup further with custom Game Mode and macros. A USB 2.0 pass-through provides an extra USB port for your multi-tasking needs. The Alloy Elite 2’s sturdy steel frame makes it durable enough for work and play day in and day out.\n", Arrays.asList("RGB Backlighting", "Customizable with NGENUITY Software", "HyperX Pudding Keycaps (ABS)"), Arrays.asList("Black"), Arrays.asList("https://hyperx.com/cdn/shop/files/hyperx_alloy_elite_2_us_1_top_down_renamed_4_1080x.jpg?v=1688317920", "https://hyperx.com/cdn/shop/files/hyperx_alloy_elite_2_us_2_angled_left_renamed_2_1080x.jpg?v=1688317920", "https://hyperx.com/cdn/shop/files/hyperx_alloy_elite_2_us_4_side_renamed_0_1080x.jpg?v=1688317920", "https://hyperx.com/cdn/shop/files/hyperx_alloy_elite_2_us_2_angled_left_renamed_2_1080x.jpg?v=1688317920"), 190.99, 8);

            Component keyboardHyperX2 = new Component("Keyboard", "HyperX", "Alloy Core RGB Membrane Gaming Keyboard", "Featuring HyperX’s signature radiant light bar, and smooth, dynamic RGB lighting effects, the HyperX Alloy Core RGB™ is ideal for gamers looking to enhance their keyboard’s style and performance without breaking the bank. With six different lighting effects and three brightness levels, it balances both brilliance and budget. Crafted with a durable, reinforced plastic frame, the Alloy Core RGB was constructed for stability and reliability for gamers who want a keyboard that will last. The soft-touch keys have a tactile feel, yet are tuned to be quiet, and they also feature gaming-grade anti-ghosting functionality and key rollover. It’s spill resistant, tested to withstand 120ml of liquid, so beverage accidents won’t put an end to your game. The dedicated media controls and quick access buttons for lighting and Game Mode place control right at your fingertips. Keyboard Lock allows you to lock your keyboard down without having to put your entire system on standby. The Alloy Core RGB is stylish, nicely-featured, and durable, making it a great all-around multimedia keyboard for gamers.", Arrays.asList("RGB Backlighting", "Quiet, responsive keys", "Signature light bar and dynamic RGB lighting effects"), Arrays.asList("Black"), Arrays.asList("https://row.hyperx.com/cdn/shop/products/hyperx_alloy_core_rgb_ru_1_main_1080x.jpg?v=1664011586", "https://row.hyperx.com/cdn/shop/products/hyperx_alloy_core_rgb_2_jp_left_1080x.jpg?v=1664011586", "https://row.hyperx.com/cdn/shop/products/hyperx_alloy_core_rgb_3_jp_right_1080x.jpg?v=1664011586", "https://row.hyperx.com/cdn/shop/products/hyperx_alloy_core_rgb_4_jp_side_1080x.jpg?v=1664011586"), 39.99, 100);

            Component microphoneHyperX1 = new Component("Microphone", "HyperX", "QuadCast S – USB Condenser Gaming Microphone", "The HyperX QuadCast™ S is a USB condenser microphone that both sounds great and looks great. The supremely stunning RGB lighting and dynamic effects will add style and flair to any stream or setup and is customizable via HyperX NGENUITY software. The QuadCast S is an all-inclusive mic, featuring an anti-vibration shock mount to help quiet the rumbles of daily life and a built-in pop filter to muffle plosive sounds. Instantly know your mic status with the LED indicator, and simply tap-to-mute to avoid awkward broadcasting accidents. With four selectable polar patterns, this mic’s prepared for nearly any recording situation and also features a gain control dial to quickly regulate input sensitivity. The included mount adapter fits 3/8” and 5/8” thread sizes, compatible with most stands. QuadCast S is certified by Discord and TeamSpeak™ so you can ensure that your microphone is broadcasting loud and clear for all your followers and listeners, and you can also monitor your mic in real time using the convenient headphone jack on the back of the mic. It’s multi-platform compatible, so you can deliver quality sound output whether you’re connecting to a PC, PS5™, PS4™, or Mac®.", Arrays.asList("RGB Backlighting", "Customizable with NGENUITY Software", "Tap-to-Mute Sensor with LED indicator", "Stereo, Omnidirectional, Cardioid, Bidirectional"), Arrays.asList("Black", "White"), Arrays.asList("https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_s_2_side_1080x.jpg?v=1662435227", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_s_6_back_features_1080x.jpg?v=16624352276", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_s_5_mute_1080x.jpg?v=1662435227", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_s_white_7_accessories_1080x.jpg?v=1662435227", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_s_white_4_angled_1080x.jpg?v=1662435227"), 129.99, 100);

            Component microphoneHyperX2 = new Component("Microphone", "HyperX", "DuoCast USB Microphone", "Featuring an elegant design, a low-profile shock mount, and a tasteful RGB light ring, the HyperX DuoCast is a full-featured USB microphone that’s built for gaming, working, and content creation. It shares the fan-favorite features of its HyperX mic siblings, such as tap-to-mute, and the vibrant LED mic mute indicator, but also brings its own unique, subtle style. A low-profile shock mount complements the sleek, minimalist aesthetic, while also absorbing vibrations, and taking up less space. An included mount adapter allows for compability with most mounts and the versatile DuoCast is also compatible with PC, PS5™, PS4™, and Mac®. Use HyperX NGENUITY Software and customize the RGB light ring to broadcast your own signature style.", Arrays.asList("RGB Backlighting", "Customizable with NGENUITY Software", "Tap-to-Mute Sensor with LED indicator", "Cardioid, Omnidirectional"), Arrays.asList("Black"), Arrays.asList("https://row.hyperx.com/cdn/shop/products/hyperx_duocast_2_side_1080x.jpg?v=1662449659", "https://row.hyperx.com/cdn/shop/products/hyperx_duocast_4_tilt_1080x.jpg?v=1662449659", "https://row.hyperx.com/cdn/shop/products/hyperx_duocast_5_features_1080x.jpg?v=1662449659", "https://row.hyperx.com/cdn/shop/products/hyperx_duocast_6_inner_mount_1080x.jpg?v=1662449659", "https://row.hyperx.com/cdn/shop/products/hyperx_duocast_7_accessories_1080x.jpg?v=1662449659"), 69.99, 100);

            Component headphoneHyperX1 = new Component("Headphone", "HyperX", "Cloud III - Gaming Headset", "The HyperX Cloud III is an evolution of our legendary Cloud II, which is known for its comfort, sound quality and durability. With plush HyperX signature memory foam in the headband and ear cushions, it provides a comfortable fit perfect for long gaming sessions. It also features new, retuned 53mm drivers that are angled for an optimal listening experience. The upgraded 10mm microphone captures crystal clear in-game voice chat and calls. Simple controls on the headset earcup allow you to have quick, direct access to mute your mic or adjust audio volume. The LED mic mute clearly shows when you’re muted. Compatible with PC, PS5, Xbox Series X|S, Xbox One, Nintendo Switch, Mac, and Mobile. Experience ultimate comfort and sound across your favorite platforms.", Arrays.asList("HyperX Signature Comfort and Durability", "Angled 53mm Drivers, Tuned for Impeccable Audio", "Crystal-Clear 10mm microphone, noise-cancelling, with LED mic-mute indicator", "Multiplatform Compatible with 3.5mm, USB-C, and USB-A\n"), Arrays.asList("Black-Red", "Black"), Arrays.asList("https://row.hyperx.com/cdn/shop/files/hyperx_cloud_iii_red_66x0049_main_1_1080x.jpg?v=1692736987", "https://row.hyperx.com/cdn/shop/files/hyperx_cloud_iii_red_66x0049_angle_6_1080x.jpg?v=1692736987", "https://row.hyperx.com/cdn/shop/files/hyperx_cloud_iii_black_66x0048_angle_4_1080x.jpg?v=1692736987", "https://row.hyperx.com/cdn/shop/files/hyperx_cloud_iii_black_66x0048_angle_7_1080x.jpg?v=1692736987", "https://row.hyperx.com/cdn/shop/files/hyperx_cloud_iii_black_66x0048_angle_5_1080x.jpg?v=1692736987"), 99.99, 100);

            Component headphoneHyperX2 = new Component("Headphone", "HyperX", "Cloud Stinger - Comfortable Gaming Headset for PS5 and PS4", "HyperX Cloud Stinger™ is an Official PlayStation® Licensed headset, perfect for PS5™ and PS4™ gamers looking for comfort, superior sound quality, and convenience. It’s lightweight and features signature HyperX memory foam for legendary comfort during marathon gaming sessions. Its 90° rotating ear cups can rest comfortably around your neck during breaks. 50mm directional drivers pump out high-quality sound with pinpoint audio precision to keep you immersed in gaming. For added convenience, the headset has a volume slider on the ear cup and a swivel-to-mute noise-cancellation microphone.", Arrays.asList("Official PlayStation® licensed headset", "Lightweight with 90-degree rotating ear cups", "HyperX Signature comfort and durability", "Swivel-to-mute noise-cancelling mic"), Arrays.asList("Black-Blue"), Arrays.asList("https://row.hyperx.com/cdn/shop/products/hyperx_cloud_stinger_ps4_2_extended_1080x.jpg?v=1662435227", "https://row.hyperx.com/cdn/shop/products/hyperx_cloud_stinger_ps4_4_rotated_1080x.jpg?v=1662435227", "https://row.hyperx.com/cdn/shop/products/hyperx_cloud_stinger_ps4_5_rotated_flat_1080x.jpg?v=1662435227", "https://row.hyperx.com/cdn/shop/products/hyperx_cloud_stinger_ps4_4_rotated_31_1080x.jpg?v=1662435227", "https://row.hyperx.com/cdn/shop/products/hyperx_cloud_stinger_ps4_3_side_1080x.jpg?v=1662435227"), 49.99, 100);


            componentRepository.save(mouseHyperX1);
            componentRepository.save(mouseHyperX2);
            componentRepository.save(microphoneHyperX1);
            componentRepository.save(microphoneHyperX2);
            componentRepository.save(keyboardHyperX1);
            componentRepository.save(keyboardHyperX2);
            componentRepository.save(headphoneHyperX1);
            componentRepository.save(headphoneHyperX2);

            Component microphoneLogitech1 = new Component("Microphone", "Logitech", "Yeti GX", "Yeti GX is a premium RGB gaming mic powered by LIGHTSYNC and designed specifically for game streamers. Combining a custom dynamic capsule with advanced software, this USB microphone rejects noise and key clicks, improves your sound and ensures consistent high-quality audio while you stream.", Arrays.asList("Lightsync RGB","Dynamic Supercardoid Mic Capsule", "Broadcast-Quality Audio"), Arrays.asList("Black"), Arrays.asList("https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_03_back_1080x.jpg?v=1662449692", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_04_angled_1080x.jpg?v=1662449692", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_05_muted_1080x.jpg?v=1662449692", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_07_accessories_1080x.jpg?v=1662449692", "https://row.hyperx.com/cdn/shop/products/hyperx_quadcast_06_back_features_1080x.jpg?v=1662449692"), 149.99, 100);

            Component microphoneLogitech2 = new Component("Microphone", "Logitech", "BLUE SONA", "Blue Sona is a new kind of XLR dynamic microphone designed for game streamers and podcasters. With ClearAmp technology, an innovative capsule and a modern, camera-ready aesthetic, Blue Sona brings out the best in every voice and creates a true studio-quality stream experience.", Arrays.asList("Dual-Diaphragm Mic Capsule","Internal Shockmount", "Supercardoid and Super Quiet"), Arrays.asList("White"), Arrays.asList("https://resource.logitech.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/microphones/blue-sona/gallery/blue-sona-microphones-quarter-right-view-off-white.png?v=1", "https://resource.logitech.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/microphones/blue-sona/gallery/blue-sona-microphones-right-view-off-white.png?v=1", "https://resource.logitech.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/microphones/blue-sona/gallery/blue-sona-microphones-quarter-back-view-off-white.png?v=1", "https://resource.logitech.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/microphones/blue-sona/gallery/blue-sona-microphones-back-view-off-white.png?v=1", "https://resource.logitech.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/microphones/blue-sona/gallery/blue-sona-microphones-front-view-off-white.png?v=1"), 349.99, 100);

            Component mouseLogitech1 = new Component("Mouse", "Logitech", "G705", "From the Aurora Collection, G705 Wireless Gaming Mouse is contoured for comfort and control with an intentional design to be inclusive of smaller hands. Features gaming-grade LIGHTSPEED wireless, LIGHTSYNC RGB, and advanced gaming technology.", Arrays.asList("Shaped For Comfort","Wireless", "Compact and Power-Packed"), Arrays.asList("White"), Arrays.asList("https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/mouse/g705-wireless-mouse/gallery/g705-gallery-1.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/mouse/g705-wireless-mouse/gallery/g705-gallery-2.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/mouse/g705-wireless-mouse/gallery/g705-gallery-3.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/mouse/g705-wireless-mouse/gallery/g705-gallery-4.png?v=1"), 199.99, 100);

            Component mouseLogitech2 = new Component("Mouse", "Logitech", "G903", "Ultimate gaming mouse. Ultralow-latency LIGHTSPEED wireless. HERO 25K sensor achieves sub-micron tracking. Ambidextrous design. Hyper-fast scrollwheel. POWERPLAY compatible for continuous wireless charging.", Arrays.asList("Ambidextrous - Up to 11 Buttons","Pro-Grade Wireless", "1:1 TRACKING, 25,600 MAX DPI"), Arrays.asList("Black"), Arrays.asList("https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/g903/g903-gallery-1.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/g903/g903-gallery-2.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/g903/g903-gallery-3.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/hawk-g903-hero/g903-gallery-4-nb.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/g903/g903-gallery-5.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/hawk-g903-hero/g903-gallery-6-nb.png?v=1"), 129.99, 100);

            Component keyboardLogitech1 = new Component("Keyboard", "Logitech", "PRO X TKL", "A championship-trusted wireless gaming keyboard designed for the highest levels of competitive play. Designed with pros and engineered to win.", Arrays.asList("RGB lighting with LIGHTSYNC","NEW Game Mode Lock function", "Designed for Pros to Win Championships"), Arrays.asList("Pink", "Black", "White"), Arrays.asList("https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-tkl/gallery-1-pro-x-tkl-magenta-lightspeed-gaming-keyboard.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-tkl/gallery-2-pro-x-tkl-magenta-lightspeed-gaming-keyboard.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-tkl/gallery-1-pro-x-tkl-white-lightspeed-gaming-keyboard.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-tkl/gallery-2-pro-x-tkl-white-lightspeed-gaming-keyboard.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-tkl/gallery-2-pro-x-tkl-black-lightspeed-gaming-keyboard.png.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-tkl/gallery-4-pro-x-tkl-black-lightspeed-gaming-keyboard.png.png?v=1"), 199.99, 100);

            Component keyboardLogitech2 = new Component("Keyboard", "Logitech", "G413", "Designed for advanced performance with the right feature set. The bladelike chassis is made of high-strength aluminum alloy with USB passthrough, backlit keys, Romer-G tactile mechanical switches, and more.", Arrays.asList("Precision Key Lighting","Aircraft-Grade Aluminium Alloy", "Advanced Gaming Features"), Arrays.asList("Silver", "Black"), Arrays.asList("https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/g413-firebird/g413-mechanical-gaming-keyboard-gallery-1.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/g413-firebird/g413-mechanical-gaming-keyboard-gallery-3.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/g413-firebird/g413-mechanical-gaming-keyboard-gallery-4.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/g413-firebird/g413-gallery-1-nb.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/g413-firebird/g413-gallery-2-nb.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/non-braid/g413-firebird/g413-gallery-3-nb.png?v=1"), 69.99, 2);

            Component headphoneLogitech1 = new Component("Headphone", "Logitech", "PRO X 2 LIGHTSPEED", "Designed with pros. Engineered to win. PRO X 2 LIGHTSPEED headset features pro-grade sound, LIGHTSPEED wireless, and supreme comfort for the highest levels of competition. Hear every footstep, action, and pin pull with the immersive soundscape enabled by graphene drivers.", Arrays.asList("50mm Graphene Drivers","Lightspeed Wireless", "6mm Cardioid Microphone"), Arrays.asList("Pink", "Black", "White"), Arrays.asList("https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-2-lightspeed/gallery/gallery-1-pro-x-2-lightspeed-gaming-headset-black.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-2-lightspeed/gallery/gallery-3-pro-x-2-lightspeed-gaming-headset-black.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-2-lightspeed/gallery/gallery-3-pro-x-2-lightspeed-gaming-headset-magenta.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-2-lightspeed/gallery/gallery-5-pro-x-2-lightspeed-gaming-headset-magenta.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-2-lightspeed/gallery/gallery-6-pro-x-2-lightspeed-gaming-headset-white.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/pro-x-2-lightspeed/gallery/gallery-1-pro-x-2-lightspeed-gaming-headset-white.png?v=1"), 249.99, 100);

            Component headphoneLogitech2 = new Component("Headphone", "Logitech", "Logitech FITS", "Logitech G FITS mold to give you a personal fit. No matter what size your ears are. Whether you like to be immersed in PC, mobile or console games. And no matter what hair styles or hats you like to wear, FITS create an individualized experience that adapts to you and how you like to play.", Arrays.asList("Pro-Grade Lightspeed and Low Latency Bluetooth Connectivity","Lightform Moulding with Patented LIGHTFORM technology", "Four Built-In Beamforming Microphones."), Arrays.asList("Black", "White"), Arrays.asList("https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/fits/gallery/gallery-1-black.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/fits/gallery/gallery-4-black.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/fits/gallery/gallery-7-black.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/fits/gallery/gallery-1-white.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/fits/gallery/gallery-2-white.png?v=1", "https://resource.logitechg.com/w_572,c_lpad,ar_4:3,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/gaming/en/products/fits/gallery/gallery-4-white.png?v=1"), 229.99, 100);



            componentRepository.save(microphoneLogitech1);
            componentRepository.save(microphoneLogitech2);
            componentRepository.save(mouseLogitech1);
            componentRepository.save(mouseLogitech2);
            componentRepository.save(keyboardLogitech1);
            componentRepository.save(keyboardLogitech2);
            componentRepository.save(headphoneLogitech1);
            componentRepository.save(headphoneLogitech2);

            Component headphoneAstro1 = new Component("Headphone", "Astro", "Astro A50", "Experience the performance and sound of ASTRO Audio V2 with the convenience and freedom that comes without wires. The A50 Wireless Headset for Xbox, PlayStation, and PC/Mac delivers top-of-the-line acoustics, ergonomics, and durability that professional gamers demand with the revolutionary, iconic ASTRO Gaming design. Experience Absolute Immersion with the A50 Wireless + Base Station.", Arrays.asList("Built-In MixAmp","Flip to Mute Microphone", "Dolby Audio"), Arrays.asList("Black-Gold", "Black-Grey"), Arrays.asList("https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a50-headset-with-base-station-gen4/a50-gallery-xbox-01.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a50-headset-with-base-station-gen4/a50-gallery-xbox-02.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a50-headset-with-base-station-gen4/a50-gallery-xbox-03.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a50-headset-with-base-station-gen4/a50-gallery-ps4-04-refresh.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a50-headset-with-base-station-gen4/a50-gallery-ps4-05-refresh.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a50-headset-with-base-station-gen4/a50-gallery-ps4-01-refresh.png?v=1"), 299.99, 100);

            Component headphoneAstro2 = new Component("Headphone", "Astro", "Astro A20", "The A20 Wireless Gen 2 is designed to give you freedom on several levels. Its 2.4 GHz signal provides an extended wireless range and with the flip-to-mute microphone you can easily choose if you want to be heard or not. Additionally, the headset’s long-lasting comfort and battery life allow you to game through those marathon sessions. You can even add an extra USB transmitter for PlayStation 5 or Xbox Series X for an expanded console compatibility, which means you never have to switch headsets again. ", Arrays.asList("15M Wireless Range","Tuned with Astro Audio V2", "15+ Hours Battery Life"), Arrays.asList("Blue-White", "Green-White"), Arrays.asList("https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a20-wireless-gen-2-headset/a20-gallery-xbox-01.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a20-wireless-gen-2-headset/a20-gallery-xbox-02.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a20-wireless-gen-2-headset/a20-gallery-xbox-03.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a20-wireless-gen-2-headset/a20-gallery-ps4-01.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a20-wireless-gen-2-headset/a20-gallery-ps4-02.png?v=1", "https://resource.astrogaming.com/w_849,c_limit,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/astro/en/products/a20-wireless-gen-2-headset/a20-dongle-2020-on-transparent-gallery-ps.png?v=1"), 199.99, 100);

            Component mouseZowie1 = new Component("Mouse", "Zowie", "EC3-CW Wireless Mouse For Esports", "EC's trademark shape is a very widely used option for players who prefer asymmetrical ergo design.The top shell provides a natural curve for your hand with a relaxed support to your palm and fingers, providing more stability when moving horizontally. EC's classic shape has not-too-much palm contact and can accommodates different grip styles with comfortable posture. Reduce the fatigue of flexor carpi ulnaris muscle (FCU) when doing fast clicking", Arrays.asList("Wireless design with enhanced receiver","Asymmetrical ergonomic design with shorter overall length", "Reduced weight; 24-step scroll wheel", "Driverless; plug and play"), Arrays.asList("Black"), Arrays.asList("https://image.benq.com/is/image/benqco/01-ec3-cw-top?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/04-ec3-cw-back-left-45?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/06-ec3-cw-right?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/08-ec3-cw-rx?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/07-rx-2?$ResponsivePreset$&fmt=png-alpha"), 149.99, 100);

            Component mouseZowie2 = new Component("Mouse", "Zowie", "EC1-CW Wireless Mouse For Esports", "EC's trademark shape is a very widely used option for players who prefer asymmetrical ergo design.The top shell provides a natural curve for your hand with a relaxed support to your palm and fingers, providing more stability when moving horizontally. EC's classic shape has not-too-much palm contact and can accommodates different grip styles with comfortable posture. Reduce the fatigue of flexor carpi ulnaris muscle (FCU) when doing fast clicking", Arrays.asList("Wireless design with enhanced receiver","Asymmetrical ergonomic design with shorter overall length", "Reduced weight; 24-step scroll wheel", "Driverless; plug and play"), Arrays.asList("Black"), Arrays.asList("https://image.benq.com/is/image/benqco/01-ec1-cw-top?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/02-ec1-cw-bottom?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/03-ec1-cw-back-left-45?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/04-ec1-cw-front-left-45?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/06-ec1-cw-right?$ResponsivePreset$&fmt=png-alpha", "https://image.benq.com/is/image/benqco/08-ec1-cw-rx?$ResponsivePreset$&fmt=png-alpha"), 129.99, 100);

            Component keyboardGamdia1 = new Component("Keyboard", "Gamdia", "HERMES P2", "The HERMES P2 is an optical-mechanical gaming keyboard with all the features of a premium mechanical keyboard. Featuring the all-new speedy and responsive optical gaming switches, 16.8 million RGB backlit, a solid metal backplate and a comfortable ergonomic wrist rest. The keyboard features a solid metal faceplate for lightweight stability and a built-in ergonomic wrist rest for maximum comfort.", Arrays.asList("Anti-ghosting with N-key rollover", "Metal back plating Mechanical Keyboard", "Ergonomic Wrist Rest", "GAMDIAS Certified Mechanical Optical Switches"), Arrays.asList("Black"), Arrays.asList("https://www.gamdias.com/img/keyboard/HERMES_P2/HERMES_P2_Slogan.png", "https://www.gamdias.com/img/keyboard/HERMES_P2/HERMES_P2_Exh1.jpg", "https://www.gamdias.com/img/keyboard/HERMES_P2/HERMES_P2_Exh2.jpg", "https://www.gamdias.com/img/keyboard/HERMES_P2/HERMES_P2_Exh3.jpg"), 149.99, 100);

            Component keyboardGamdia2 = new Component("Keyboard", "Gamdia", "HERMES M6", "SLEEK. PRECISE. DOMINANT. The HERMES M6 is a premium mechanical keyboard with a stylish posh metallic-textured brush-up backplate adjoined by two LED streaming lights matched with efficient and tactile feedback on each keystroke to help you get the job done. Bring vivid and brilliant illumination to the battlefield with seven built-in lighting effects and six color backlighting, along with two sky blue LED streaming lights on both wings of the keyboard to keep you in rhythm.", Arrays.asList("Multi colors backlights", "GAMDIAS Certified Mechanical Switches", "Ergonomic design", "Aluminum bezel"), Arrays.asList("White"), Arrays.asList("https://www.gamdias.com/img/keyboard/HERMES_M6/HERMES_M6_Slogan.png", "https://www.gamdias.com/img/keyboard/HERMES_M6/HERMES_M6_Exh1.jpg", "https://www.gamdias.com/img/keyboard/HERMES_M6/HERMES_M6_Exh2.jpg", "https://www.gamdias.com/img/keyboard/HERMES_M6/HERMES_M6_Exh3.jpg"), 129.99, 1);

            Component microphoneRode1= new Component("Microphone", "Rode", "PodMic USB", "The PodMic USB is an ultra-versatile dynamic microphone ideal for podcasting, streaming, gaming, voice overs, and other speech applications for content creation. It delivers rich, full-bodied sound and features both an XLR and USB output for connecting to an audio interface or mixer like a classic broadcast microphone, or directly to a computer for plug-and-play recording. The digital USB output features RØDE’s ultra-low-noise, high-gain Revolution Preamp™ and powerful APHEX® digital signal processing for capturing studio-quality sound with ease, and a zero-latency headphone output complete with level control, making recording seamless. For even more versatility, the PodMic USB is also fully compatible with iOS and Android mobile devices, offering a high-quality portable podcasting or streaming solution", Arrays.asList("Ultra-low-noise, high-gain Revolution Preamp", "Analog XLR and digital USB-C connectivity", "Fully compatible with Windows and Mac computers, and iOS and Android devices", "Broadcast-quality dynamic microphone"), Arrays.asList("Black"), Arrays.asList("https://edge.rode.com/images/page/2124/modules/7967/rode-podmic-usb-black-rear-4000x4000-rgb-2000x2000-aee9093.png", "https://edge.rode.com/images/page/2124/modules/11/rode-podmic-usb-black-hero-3-quater-4000x4000-rgb-2000x2000-064a3d6.png", "https://edge.rode.com/images/page/2124/modules/11/rode-podmic-usb-black-hero-3-quater-tilted-4000x4000-rgb-2000x2000-064a3d6.png", "https://edge.rode.com/images/page/2124/modules/7967/rode-podmic-usb-black-hero-front-on-4000x4000-rgb-2000x2000-5247177.png", "https://edge.rode.com/images/page/2124/modules/7967/rode-podmic-usb-main-inputs-tiled-forward-gold-4000x4000-rgb-2000x2000-e42ff96.png"), 199.99, 100);

            Component microphoneRode2= new Component("Microphone", "Rode", "NT-USB", "The NT-USB is a professional USB condenser microphone that delivers exceptional performance for recording vocals and instruments, gaming and livestreaming, podcasting, voice-overs and more. Offering impeccable audio, elegant looks and premium features, all in an easy-to-use form factor, the NT-USB will have you sounding like a pro in seconds", Arrays.asList("Professional USB condenser microphone", "Professional pop filter and tripod included", "High-power headphone output for zero-latency", "On-board monitor level and headphone mix controls"), Arrays.asList("Black"), Arrays.asList("https://edge.rode.com/images/page/349/modules/1225/R%C3%98DE_NT-USB_3_QUARTER_FRONT_1080x1080.png", "https://edge.rode.com/images/page/349/modules/1225/R%C3%98DE_NT-USB_Front_1080x1080.png", "https://edge.rode.com/images/page/349/modules/1225/R%C3%98DE_NT-USB_3_QUARTER_BACK_1080x1080.png", "https://edge.rode.com/images/page/349/modules/1225/R%C3%98DE_NT-USB_3_QUARTER_FRONT_1080x1080.png"), 249.99, 100);


            componentRepository.save(headphoneAstro1);
            componentRepository.save(headphoneAstro2);
            componentRepository.save(mouseZowie1);
            componentRepository.save(mouseZowie2);
            componentRepository.save(keyboardGamdia1);
            componentRepository.save(keyboardGamdia2);
            componentRepository.save(microphoneRode1);
            componentRepository.save(microphoneRode2);



//            Buy buyPrueba = new Buy(2,120.0);
//            Buy buyPrueba2 = new Buy(4,240.0);
//            Ticket ticketPrueba = new Ticket("2",120.0, LocalDateTime.now(), BuyType.DEBIT);
//            Ticket ticketprueba2 = new Ticket("6775",240.0, LocalDateTime.now(), BuyType.CREDIT);

//            julianBrunelli.addTicket(ticketPrueba);
//            ticketRepository.save(ticketPrueba);

//            ticketPrueba.addBuy(buyPrueba);
//            buyRepository.save(buyPrueba);
//
//            mouseHyperX1.addBuy(buyPrueba);
//            buyRepository.save(buyPrueba);

//            Client gabrielBarbera = new Client("GabrielBarbera@outlook.com", "1234", 20056784, 1925, "36 e/ 123 y 124", "115351458");
//            clientRepository.save(gabrielBarbera);
//
//            gabrielBarbera.addTicket(ticketprueba2);
//            ticketRepository.save(ticketprueba2);
//
//            ticketprueba2.addBuy(buyPrueba2);
//            buyRepository.save(buyPrueba2);
//
//            mouseHyperX1.addBuy(buyPrueba2);
//            buyRepository.save(buyPrueba2);

            Client maximilianoLedesma = new Client("MaximilianoLedesma@outlook.com", "1234", 21056784, 1925, "36 e/ 123 y 124", "115351456");
            clientRepository.save(maximilianoLedesma);

            Client alanisLobato = new Client("AlanisLobato@outlook.com", "1234", 43417900, 1925, "36 e/ 123 y 124", "2216204142");
            clientRepository.save(alanisLobato);

            Client darylBaptie = new Client("DarylBaptie@outlook.com", "1234", 35042684, 1925, "36 e/ 123 y 124", "114972353");
            clientRepository.save(darylBaptie);


        };
    }

}